/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json2csv;

import java.io.File;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JsonFileReaderTest {
    @Test
    public void ShouldReturnStringOfFile(){
        File file = new File(
            getClass().getClassLoader().getResource("test.json").getFile()
        );
        JsonFileReader reader = new JsonFileReader();
        assertNotNull(reader.read(file));
        assertEquals("{}", reader.read(file));
        file = new File(
            getClass().getClassLoader().getResource("test2.json").getFile()
        );
        assertEquals("{ \"name\" : \"john\" }", reader.read(file));
    }

    @Test
    public void ShouldReturnEmptyStringIfFileIsNull(){
        JsonFileReader jsr = new JsonFileReader();
        assertEquals("", jsr.read(null));
    }
}
